### PR TITLE
Added L10 support

### PR DESCRIPTION
**Pull request by SuperDJ**
- Added L10 Support https://github.com/Ricorocks-Digital-Agency/Soap/issues/59;
- Added PHP8.2 support;

### CODE REVIEW

**Comment by SuperDJ** [comment]
ping @lukeraymonddowning

**Comment by lukeraymonddowning** [comment]
@SuperDJ thanks for the PR! Are you able to update the workflow with an include for testbench/L10 to fix the failing checks?

**Comment by SuperDJ** [comment]
@lukeraymonddowning have added Laravel 10 and testbench 8 to the include test matrix

**Comment by lukeraymonddowning** [comment]
Thanks very much for the PR @SuperDJ 🚀 Merged and released.

**Pull request merged**
